### ISSUE TITLE
Enabling translation results in existing pages being flagged a changed.

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#29] opened 2012-06-17 11:55 UTC
Migrated from http://open.silverstripe.org/ticket/4071

After enabling translations, existing pages are flagged as changed requiring them to be re-published. (Not sure: Perhaps this is by design?)

**Comment by robbieaverill** [comment] 2018-03-28 00:28
I hate to do this, but we've had a report that this is still an issue in the 2.3.x release line. The commit from #171 was made in master and since we've not released a minor version since then it has never been released. We possibly just need to cherry pick it and release as 2.3.1

**Comment by robbieaverill** [comment] 2018-04-20 04:28
Reproduced on translatable 2.2.x-dev and SS 3.6.x. Test process:

* Set up a fresh SS project
* Check CMS SiteTree, all pages are published
* Install translatable, run sake dev/build flush=1
* Check CMS SiteTree, all pages are in draft

Expected: pages should retain their existing state
Actual: all pages are set to draft

**Comment by robbieaverill** [comment] 2018-04-20 04:32
39b1bc64925b4a5f388de76b399065950e9ae154 via #171 verified as the fix for this. I'll cherry pick it and release it under 2.2.x

**Comment by robbieaverill** [comment] 2018-04-20 04:41
Released as 2.2.6 and 2.3.1

**Closed by robbieaverill** 2018-04-20 04:41 UTC
Labels: affects/v3, change/patch, effort/easy, impact/medium, type/bug
