### ISSUE TITLE
Click pages tab

### ISSUE THREAD

**Issue by mmichelli** [silverstripe/silverstripe-translatable#173] opened 2014-11-20 13:37 UTC
In the newest version of Silverstripe, translatable's redirect "?locale=nb_NO" breaks the pjax call on the "Pages" button. 

The loadPanel javascript function loads a blank page, not the redirected to content. 

$('.cms-menu-list li a').entwine
...
if(!$('.cms-container').loadPanel(url)) return false;

**Comment by chillu** [comment] 2015-01-03 23:42
Tested on the latest 3.1 branch and the latest translatable 1.1 branch. 

- Create a new "Norwegian" translation of a page (e.g. `/admin/pages/edit/show/2`)
- CMS redirects to the edit view of that page (e.g. `/admin/pages/edit/show/7?locale=nb_NO`)
- Click the "Pages" menu entry, redirects to `/admin/pages/`, then to '/admin/pages/?locale=en_US`, then to `/admin/pages/show/2?locale=en_US`.

So that's inconsistent in two ways: First its no longer respecting the language choice, then then it redirects to a detail URL, but shows the view content of `/admin/pages`.

Does that describe your bug?

**Comment by mmichelli** [comment] 2015-01-05 12:24
Yes, those are two bugs. But my issue is that it loads a blank page, because the redirects are not shown but are loaded by the PJAX

**Comment by chillu** [comment] 2015-01-05 19:08
Which browser? JS errors? Can you please paste the full HTTP request/response from web dev tools here? Maybe even a HTML dump of the page you're viewing (so copy the "Edit as HTML" in the "Elements" panel)

**Comment by mmichelli** [comment] 2015-01-07 09:49
After clicking on the pages ("Sider") tab button 
Result: 
![screen shot 2015-01-07 at 10 38 07](https://cloud.githubusercontent.com/assets/82415/5643488/559ba854-9659-11e4-879d-70c20e37f3c9.png)

"Pages/" response: 
![screen shot 2015-01-07 at 10 39 43](https://cloud.githubusercontent.com/assets/82415/5643517/a6c62466-9659-11e4-9a8a-9b6fbd63f9b4.png)

"?local=nb_NO" response:
 {"Content":"<div id=\"pages-controller-cms-content\" class=\"cms-content center cms-tabset ....
![screen shot 2015-01-07 at 10 42 40](https://cloud.githubusercontent.com/assets/82415/5643542/f45f585a-9659-11e4-9391-df7b3946ff0c.png)

Network: 
![screen shot 2015-01-07 at 10 35 48](https://cloud.githubusercontent.com/assets/82415/5643466/1b804ab2-9659-11e4-98a6-27be4d69c857.png)

Browser:
Firefox and Chrome

No javascript errors 

This is only an issue when PJAX is used, if I refresh the page there is no issue. 

After I press the "pages" tab button, all the other tabs stop loading. (The PJAX stops working)

**Comment by chillu** [comment] 2015-01-07 09:51
Why is it going to `pages/` rather than `admin/pages`? Have you customised the menu somehow? Is that the link in the `<a href>` of the menu entry as well?

**Comment by mmichelli** [comment] 2015-01-07 10:08
This is not a blank install, but I'm having the same issue with all the sites that run the latest Silverstripe and translatable. I've not done anything to the sidebar. 

The issue is with pages redirects and PJAX. They not playing well together. 

![screen shot 2015-01-07 at 11 04 38](https://cloud.githubusercontent.com/assets/82415/5643811/23aabf20-965d-11e4-8e3f-609a6e5685b9.png)

**Comment by mmichelli** [comment] 2015-01-07 10:10
I guess the inspector is just showing relative paths, so skipped off admin.

**Comment by franktakes** [comment] 2016-07-07 11:47
I have the exact same problem, it fails on the async call but works fine if you press F5.
I also have made no custom adjustments.
Has this issue been solved yet, or is there a patch available?

**Comment by dhensby** [comment] 2016-07-07 15:30
@franktakes what version of SS are you on?

**Comment by franktakes** [comment] 2016-07-07 15:32
Latest 3.4. 
It was also a problem in 3.2 and 3.3.

**Comment by dhensby** [comment] 2016-09-13 15:41
OK - I've tried to replicate this problem using `3.4.x-dev` of SilverStripe framework/cms and translatable latest (2.2.1) and I don't have an issue with blank pages or what not.

Can someone provide me exact versions and steps they are taking to replicate the problem?

**Comment by robbieaverill** [comment] 2017-08-01 02:25
Closing since it appears to not be reproducible. @franktakes if you're still experiencing this problem please feel free to provide further information (e.g. which other modules in your ecosystem, and which version of translatable you're using) and we can reopen! Thanks!

**Closed by robbieaverill** 2017-08-01 02:25 UTC
