### ISSUE TITLE
language switches

### ISSUE THREAD

**Issue by mmichelli** [silverstripe/silverstripe-translatable#162] opened 2014-04-24 21:41 UTC
The language switches back to the default language if you add a new gird filed item
or you leave the Pages section and return to the Pages section.

**Comment by robbieaverill** [comment] 2017-08-01 03:16
Can't reproduce on 3.6.0, closing. If this is still a problem please feel free to reopen and supply the version of SS and translatable that you're using. Thanks!

**Closed by robbieaverill** 2017-08-01 03:16 UTC
