### ISSUE TITLE
Creating a translation gives a deleted page

### ISSUE THREAD

**Issue by NobrainerWeb** [silverstripe/silverstripe-translatable#194] opened 2015-06-15 07:52 UTC
2.0.8, when i create a translation from Danish to English, the created translation is marked as deleted.
If i try to click the restore button, i get a Bad request: SiteTree #6 not found.

This is not an issue with older versions (not sure how far back you need to go)

**Comment by NobrainerWeb** [comment] 2015-06-15 07:55
2.0.5 creates the translation as draft (working)

**Comment by gallexme** [comment] 2015-07-03 07:57
same here but 2.0.5 also not working

**Comment by JorisDebonnet** [comment] 2015-12-05 18:37
Does this issue still occur in the most recent versions? I can't reproduce it at least on my 3.1 and 3.2 installations.

**Comment by robbieaverill** [comment] 2017-07-31 12:03
Please reopen if this issue is still occurring. Closing for now as per the last comment.

**Closed by robbieaverill** 2017-07-31 12:03 UTC
