### ISSUE TITLE
Cannot create translation

### ISSUE THREAD

**Issue by damian-coobers** [silverstripe/silverstripe-translatable#196] opened 2015-09-03 15:36 UTC
This is an object that I want to translate to one language:
```<?php
class Speciality extends DataObject {

	private static $db = array(
		'Title' => 'Varchar(255)',
		'Content' => 'HTMLText',
	);


}
```

... and my `_config.php`:

    <?php

    ...

    Speciality::add_extension('Translatable');

Translation tab is created, I have a dropdown with all available languages, but my problem is that `Create` button is not working, there are no errors, network movement, nothing. Please, help me solve this.

**Comment by Taitava** [comment] 2015-10-17 20:29
I can confirm this, I have exactly the same problem.

**Comment by PatrickElsing** [comment] 2015-11-02 15:09
I have the same issue. But instead of a not working button, the cms displays "FormField" as literal.

**Comment by chillu** [comment] 2015-11-02 19:40
Which version of SilverStripe are you running? This has been fixed in the 3.2 branch (not in a release yet)

**Comment by PatrickElsing** [comment] 2015-11-03 09:26
I run SilverStripe Version 3.2.0 and "silverstripe/translatable": "2.1.*@dev"

**Comment by Redrazor** [comment] 2015-11-05 11:36
I have this problem also. Running SS 3.2.0 and translatable 2.1

**Comment by radek-1** [comment] 2015-11-07 17:57
I've also that problem with SS 3.2.0 and Translatable 2.1.
Does anyone have any solution? How to fix it?

**Comment by NoLdman** [comment] 2015-11-14 10:08
This error occurre due to `InlineFormAction::create()` within Translatable.php.
Unfortunately it isn't a translatable issue itself, the silverstripe-framework v3.2.0 seems to have broken the InlineFormAction.

I resolved it by converting the `InlineFormAction` to an conventional `FormAction` and removing the line containing ` $createButton->includeDefaultJS(false);`.

I have not tested the code yet for are any side-effects, but for the moment it seems to work.

**Comment by PatrickElsing** [comment] 2015-11-16 08:27
The Bug is fixed after update to Silverstripe 3.2.1.

**Comment by dhensby** [comment] 2015-11-16 11:30
> The Bug is fixed after update to Silverstripe 3.2.1.

It is indeed

**Closed by dhensby** 2015-11-16 11:30 UTC

**Comment by letsbuildafire** [comment] 2016-01-20 23:47
Still having this issue in SS 3.2.1. NoLdman's fix doesn't seem to do anything either. Vanilla SS install, Translatable is the only added module.

**Comment by tractorcow** [comment] 2016-01-21 02:20
Can you please make a new issue and provide (lots of) information about the error you're encountering please?
