### ISSUE TITLE
Translating a page corrupts umlaut characters in URL

### ISSUE THREAD

**Issue by jp-ff** [silverstripe/silverstripe-translatable#270] opened 2017-12-28 06:48 UTC
Umlaut characters in URL get corrupted whenever a page is translated, resulting in various misbehaviour (404, random redirect loops, etc.) in preview. Also, the translated page is not accessible until the URLs are manually fixed.

See the animation below for clarification.

![404](https://user-images.githubusercontent.com/6008677/34402554-fa2d71c8-ebaa-11e7-8049-3d54f0d79c19.gif)

**Comment by robbieaverill** [comment] 2019-04-05 00:56
The default behaviour is to "remove special characters", so `ü` is converted to `ue`. If you enable multibyte URLs (`URLSegmentFilter.default_allow_multibyte: true`) I can reproduce this behaviour when translating a page with an umlaut in the URL segment from German into Englis.

The original page's URL segment is encoded in the DB as `german-ho%C3%BCme` (german hoüme) and the translated page has `german-ho%25c3%25bcme-en-nz`. It looks like the duplication process might be double encoding the URL segment.

**Comment by robbieaverill** [comment] 2019-04-05 01:23
This is pretty critical since this is a module which is built to handle languages with "special characters" in their alphabets. PR at https://github.com/silverstripe/silverstripe-translatable/pull/283

**Comment by robbieaverill** [comment] 2019-04-05 03:10
Fixed in #283, will be available in the next release

**Closed by robbieaverill** 2019-04-05 03:10 UTC
Labels: affects/v3, change/patch, effort/medium, impact/high, type/bug
