### ISSUE TITLE
BUG: Creating translated pages and tree

### ISSUE THREAD

**Issue by Josua2012** [silverstripe/silverstripe-translatable#112] opened 2013-05-12 10:29 UTC
The following images show the problem.
It uses the latest version of SilverStripe 3.1 and translatable module (11/05/2013):
https://github.com/silverstripe/silverstripe-cms/tree/3.1
https://github.com/silverstripe/sapphire/tree/3.1
https://github.com/silverstripe/silverstripe-translatable
![transcreatetree01](https://f.cloud.github.com/assets/1523607/492793/bc224e9a-baee-11e2-88a8-3267e9f2260a.png)
![transcreatetree02](https://f.cloud.github.com/assets/1523607/492794/bea19a04-baee-11e2-9853-0a571730c602.png)
![transcreatetree03](https://f.cloud.github.com/assets/1523607/492795/c12e5bcc-baee-11e2-97a7-5235c5b7933c.png)
![transcreatetree04](https://f.cloud.github.com/assets/1523607/492796/c34189f2-baee-11e2-8463-2ca05b3f5720.png)
![transcreatetree05](https://f.cloud.github.com/assets/1523607/492797/c54eb5e4-baee-11e2-83d4-213d60ba1736.png)
![transcreatetree06](https://f.cloud.github.com/assets/1523607/492798/c7762be0-baee-11e2-9b54-a34c80db93da.png)

Regards,
Jose A.

**Comment by robbieaverill** [comment] 2017-08-03 21:40
Can't reproduce any more so closing. Feel free to reopen if this is still affecting anyone on more recent versions of SS and translatable.

**Closed by robbieaverill** 2017-08-03 21:40 UTC
